### PR TITLE
Adding a helm chart verion of the 102-monitor-namespaces example

### PR DESCRIPTION
**Pull request by sekka1**
Signed-off-by: garland <garlandk@gmail.com>

Hi

Would a Helm Chart deploy option be interesting as an example usage?

I found this project and thought it was pretty cool and would be useful.  However, I didn't want to build the docker images when my use case only called for a script to be inserted into the image that you already provide.  

This allows you to not have to build the image and can place the script in the  `hooks` dir and it will mount it inside of the container.

### CODE REVIEW

**Comment by diafour** [comment]
That's a great example! We are really interested in this, but i can't merge it as is, it's over complicated to be a simple example.

Please, consider this changes:
- Rename `102-monitor-namespaces-chart` to `201-run-as-helm-chart`
- Remove Dockerfile
- README:
  - Add words about helm in the first section, something like `"A helm version of [102-monitor-namespaces](https://github.com/flant/shell-operator/tree/master/examples/102-monitor-namespaces) example. Use flant/shell-operator:latest image to run shell-operator and use ConfigMap as a storage for hooks."`
  - Combine `Helm usage` section and `Run` section: remove docker commands and kubectl apply commands
  - add `--namespace` argument for the helm command. (See below)
- For simplicity, remove namespace from `values.yaml` and `_helpers.tpl`. They are not needed for this example:
  - `{{ .Values.namespace }}` can be replaced with `{{.Release.Namespace}}`
  - `{{unit.name}}` can be replaced with `{{.Chart.Name}}`
- Add checksum of a hook file to deployment's annotations to reload deployment on ConfigMap changes:
```
annotations:
        checksum/hook: {{ .Files.Get "hooks/namespace-hook.sh" | sha256sum }}
```

**Comment by sekka1** [comment]
Cool.  Just checking if you were interested first before putting more work into this and sounds like you are =).

All good suggestions.  Let me update and ill ping you with the changes.

**Comment by diafour** [comment]
@sekka1 any news? New release is coming and there is a changes in configuration, so i will update all examples.

**Comment by sekka1** [comment]
@diafour Sorry, have been busy lately and havent had time to circle back to this.  Thanks for the heads up on the updates.  I can't be sure when I will get back to this but when I do, ill pull in your updates also.

**Comment by diafour** [comment]
Changes are made in PR #65.

**Comment by diafour** [comment]
PR #65 is merged. Thanks again for your contribution!

**Pull request closed without merging**
